#https://gitlab.com/lsit-ken3239/roles/bookstore
spring:
  security:
    oauth2:
      client:
        registration:
          gitlab:
            client-id: 8ebd7335ecdd60771ce316bf6471433c7f9fa76cf0a8ad3cc234a111f76f72be
            client-secret: gloas-844c04506a2c207f8f2fd95b628793ecfcd62aa97f0a577604bd8712056e3a38
            redirect-uri: "http://localhost:8080/login/oauth2/code/gitlab"
            scope:
              - openid
              - profile
              - email
            client-name: GitLab
        provider:
          gitlab:
            issuer-uri: https://gitlab.com
